//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.FamilyTree
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "mydsl1";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"FamilyTree";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Company";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID FamilyTreeDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(FamilyTreeCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID FamilyTreeExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(FamilyTreeCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewFamilyTreeExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(FamilyTreeCommandSetId), 0x0001);
	
		// Package identifier
		public const string FamilyTreePackageId = "c43d6173-97a5-43dd-a2cb-29146c5c09bd";
		
		// Editor factory identifier
		public const string FamilyTreeEditorFactoryId = "0e496977-77cb-49b5-9678-4e74c9138360";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string FamilyTreeModelExplorerToolWindowId = "23043cf1-17d1-4e15-b7e6-e21c60f65ffc";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Company.FamilyTree
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string FamilyTreeCommandSetId = "aedafb05-43ca-459d-adc8-205ed23af7b5";
	}
}